cabal-version:      3.0
name:               aoc2019
version:            0.1.0.0
build-type:         Simple

common warnings
    ghc-options: -Wall

common common-settings
    hs-source-dirs:
        app
        src
    build-depends:
        base >= 4.22 && < 5,
        array
    default-language: Haskell2010

executable d01
    import:           warnings
    import:           common-settings
    main-is:          Day01.hs

executable d02
    import:           warnings
    import:           common-settings
    main-is:          Day02.hs
    -- other-modules:
