cabal-version:      3.0
name:               aoc2019
version:            0.1.0.0
build-type:         Simple

common common-settings
    hs-source-dirs:
        app
        src
    ghc-options: -Wall
    build-depends:
        base >= 4.22 && < 5,
        array,
        containers,
        split
    default-language: Haskell2010

executable d01
    import:           common-settings
    main-is:          Day01.hs

executable d02
    import:           common-settings
    main-is:          Day02.hs

executable d03
    import:           common-settings
    main-is:          Day03.hs

executable d04
    import:           common-settings
    main-is:          Day04.hs
